### ISSUE TITLE
Page Build issue

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/gcd6temp#2]
@philipbaileynar do you know why this page is not building?  I was going to start debugging all the broken links, but haven't been able to access the [github](https://github.com/Riverscapes/gcd6temp/settings) website:

![image](https://user-images.githubusercontent.com/30474526/34679278-bb0dd16c-f452-11e7-8166-9b2289adcfc8.png)

**Comment by philipbaileynar** [comment]
@lhaycock have you tried running Jekyll locally? The error message will tell you which page is causing the problem.

**Comment by philipbaileynar** [comment]
@lhaycock I cloned down the repo and [ran it locally using Jekyll](http://riverscapes.northarrowresearch.com/Technical_Reference/jekyll_toolbox.html#running-jekyll-locally). It immediately told me that it was a front matter issue that was 2 seconds to fix.

Please investigate page build issues using local Jekyll.

Closing this issue because the underlying issue is resolved.
